# Generated by Django 4.1.3 on 2023-02-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticServers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('static_server_login_type', models.CharField(default='', max_length=50, null=True, verbose_name='登陆方式')),
                ('static_server_ssh_ip', models.CharField(default='', max_length=50, null=True, verbose_name='内网SSH地址')),
                ('static_server_mark_tmp', models.CharField(default='', max_length=50, null=True, verbose_name='临时备注')),
                ('static_server_status', models.CharField(choices=[('0', '下线'), ('1', '在线'), ('2', '关机')], default='1', max_length=2, verbose_name='运行状态')),
                ('static_server_cpus', models.PositiveBigIntegerField(default='', null=True, verbose_name='cpu')),
                ('static_server_cpus_car', models.PositiveBigIntegerField(default='', null=True, verbose_name='cpu卡数')),
                ('static_server_mems', models.PositiveBigIntegerField(default='', null=True, verbose_name='内存')),
                ('static_server_sysdisks', models.PositiveBigIntegerField(default='', null=True, verbose_name='系统盘')),
                ('static_server_datadisks', models.PositiveBigIntegerField(default='', null=True, verbose_name='数据盘')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StaticRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'static_rooms',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='StaticNetWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'static_network',
                'ordering': ['-id'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='StaticEqcabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('static_room_name', models.CharField(default='', max_length=50, verbose_name='归属机房')),
            ],
            options={
                'db_table': 'static_eqcabs',
                'unique_together': {('name',)},
            },
        ),
    ]
