# Generated by Django 4.1.3 on 2023-02-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudServersController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('cloud_server_project_type', models.CharField(default='', max_length=50, null=True, verbose_name='业务类型')),
                ('cloud_server_cost_env', models.CharField(default='', max_length=50, null=True, verbose_name='成本归属')),
                ('cloud_server_check', models.CharField(default='0', max_length=2, verbose_name='是否核对')),
                ('cloud_server_login_type', models.CharField(default='', max_length=50, null=True, verbose_name='登陆方式')),
                ('cloud_server_cloud_belong', models.CharField(default='', max_length=50, null=True, verbose_name='云归属')),
                ('cloud_server_city', models.CharField(default='', max_length=50, null=True, verbose_name='地域')),
                ('cloud_server_cloud_id', models.CharField(default='', max_length=50, null=True, unique=True, verbose_name='实例ID')),
                ('cloud_server_ssh_ip', models.CharField(default='', max_length=50, null=True, unique=True, verbose_name='内网SSH地址')),
                ('cloud_server_pub_ip', models.CharField(default='', max_length=50, null=True, unique=True, verbose_name='公网IP')),
                ('cloud_server_owner', models.CharField(default='', max_length=50, null=True, verbose_name='责任人')),
                ('cloud_server_env_type', models.CharField(default='', max_length=50, null=True, verbose_name='环境')),
                ('cloud_server_cloud_type', models.CharField(default='', max_length=50, null=True, verbose_name='公有云版本')),
                ('cloud_server_project_region', models.CharField(default='', max_length=50, null=True, verbose_name='项目区域')),
                ('cloud_server_project_env', models.CharField(default='', max_length=50, null=True, verbose_name='项目归属')),
                ('cloud_server_number', models.CharField(default='', max_length=50, null=True, verbose_name='项目编号')),
                ('cloud_server_all_name', models.CharField(default='', max_length=50, null=True, verbose_name='项目名称')),
                ('cloud_server_small_name', models.CharField(default='', max_length=50, null=True, verbose_name='项目简称')),
                ('cloud_server_cost_money', models.FloatField(default='0.00', max_length=50, null=True, verbose_name='月成本')),
                ('cloud_product_type', models.CharField(default='', max_length=50, null=True, verbose_name='产品类型')),
                ('cloud_server_cloud_name', models.CharField(default='', max_length=50, unique=True, verbose_name='公有云实例名')),
                ('cloud_server_cpus', models.PositiveBigIntegerField(default='', null=True, verbose_name='cpu')),
                ('cloud_server_cpus_car', models.PositiveBigIntegerField(default='', null=True, verbose_name='cpu卡数')),
                ('cloud_server_mem', models.PositiveBigIntegerField(default='', null=True, verbose_name='内存')),
                ('cloud_server_sys_disks', models.PositiveBigIntegerField(default='', null=True, verbose_name='系统盘')),
                ('cloud_server_data_disks', models.PositiveBigIntegerField(default='', null=True, verbose_name='数据盘')),
                ('cloud_server_expiration_time', models.CharField(max_length=500, null=True, verbose_name='过期时间')),
                ('cloud_server_status', models.CharField(choices=[('0', '下线'), ('1', '在线'), ('2', '关机')], default='1', max_length=2, verbose_name='运行状态')),
                ('cloud_server_mark_tmp_2', models.CharField(default='', max_length=50, null=True, verbose_name='备注2')),
                ('cloud_server_mark_tmp_3', models.CharField(default='', max_length=50, null=True, verbose_name='备注3')),
                ('cloud_server_mark_tmp_4', models.CharField(default='', max_length=50, null=True, verbose_name='备注4')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CloudTypeController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'cloud_type_controller',
                'ordering': ['-id'],
                'unique_together': {('name',)},
            },
        ),
    ]
