# Generated by Django 4.1.3 on 2023-03-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_controller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectscontroller',
            old_name='m_remake',
            new_name='m_remark',
        ),
        migrations.RenameField(
            model_name='projectscontroller',
            old_name='p_remake',
            new_name='p_remark',
        ),
        migrations.RenameField(
            model_name='projectscontroller',
            old_name='t_remake',
            new_name='t_remark',
        ),
    ]
